# Generated by Django 6.0.1 on 2026-02-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payment_status_payment_stripe_price_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link_payment",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=1000,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
    ]
