# Generated by Django 6.0.1 on 2026-01-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение",
                null=True,
                upload_to="image/%Y/%m/%d/",
                verbose_name="Загрузите изображение",
            ),
        ),
    ]
