# Generated by Django 6.0.1 on 2026-02-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["id"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
